application/urls.py
from django.conf import settings
from django.contrib import admin
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import include, path
from django.views.decorators.cache import cache_page
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.contrib.sitemaps.views import sitemap
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views

urlpatterns = [
    path('api/', include("wagtail_typograf.urls")),
    path('api/', include("core.urls", namespace="api")),
    path('django-admin/', admin.site.urls),

    path('admin/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),

    path('sitemap.xml', cache_page(15 * 60)(sitemap), name="sitemap"),
]


if "debug_toolbar" in settings.INSTALLED_APPS:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('search/', search_views.search, name='search'),
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]


def robots(request):
    return render(request, "pages/robots.txt", content_type="text/plain")


def healthcheck(request):
    from application import VERSION
    return JsonResponse({
        "status": "live",
        "version": VERSION,
    })


urlpatterns = [
    path("robots.txt", robots, name="robots"),
    path("healthcheck/", healthcheck, name="healthcheck"),
] + urlpatterns

core/urls.py
from django.urls import path

from core.views import (ArtistListView, CollectionListView, ContactView,
                        DiafilmListView, GlobeCardListView, GlobePointListView,
                        ImportView, NewsListView, SubscriptionView,
                        UnsubscriptionView)

app_name = "core"


urlpatterns = [
    path("import/", ImportView.as_view(), name="import"),

    path("contact/", ContactView.as_view(), name="contact"),
    path("subscribe/", SubscriptionView.as_view(), name="subscribe"),
    path("unsubscribe/", UnsubscriptionView.as_view(), name="unsubscribe"),

    path("news/", NewsListView.as_view(), name="news"),
    path("artists/", ArtistListView.as_view(), name="artists"),
    path("diafilms/", DiafilmListView.as_view(), name="diafilms"),
    path("collections/", CollectionListView.as_view(), name="collections"),

    path("points/", GlobePointListView.as_view(), name="globe-points"),
    path("cards/", GlobeCardListView.as_view(), name="globe-cards"),
]

core/models/snippets.py
from django.core.cache import cache
from django.db import models
from django.utils import timezone
from wagtail.admin.edit_handlers import (FieldPanel, FieldRowPanel,
                                         PageChooserPanel)
from wagtail.core.fields import StreamField
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.snippets.models import register_snippet

from core.blocks import RawStreamBlock


@register_snippet
class Chunk(models.Model):
    slug = models.SlugField(
        help_text="Строка, по которой данный chunk можно использовать в шаблоне",
    )
    description = models.TextField(
        help_text="Описание для администратора, где отображается и так далее",
        blank=True,
    )

    content = StreamField(
        verbose_name="Содержание",
        block_types=RawStreamBlock,
        blank=True, null=True,
    )

    panels = [
        FieldPanel("slug"),
        FieldPanel("description"),
        FieldPanel("content"),
    ]

    def __str__(self):
        return f"Вставка {self.slug}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        from core.templatetags.chunk_tags import get_chunk
        cache.delete(get_chunk.cache_key)

    class Meta:
        verbose_name = "вставка"
        verbose_name_plural = "вставки"


@register_snippet
class Quote(models.Model):
    author = models.CharField(verbose_name="Автор", max_length=100)
    image = models.ForeignKey(
        'wagtailimages.Image', related_name='+', on_delete=models.SET_NULL,
        null=True, blank=True,
        verbose_name="Изображение",
    )
    caption = models.CharField(verbose_name="Подпись", max_length=100)
    text = models.TextField(verbose_name="Текст")
    # source = models.CharField(verbose_name="Источник", max_length=50)

    panels = [
        FieldPanel("author"),
        ImageChooserPanel("image"),
        FieldPanel("caption"),
        FieldPanel("text"),
    ]

    def __str__(self):
        return f"«{self.text}» {self.author}, {self.caption}"

    class Meta:
        verbose_name = "цитата"
        verbose_name_plural = "цитаты"


class Day(models.Model):
    """
    Для рубрики Диафильм дня
    """
    day = models.IntegerField(verbose_name="День")
    month = models.IntegerField(verbose_name="Месяц")
    description = models.CharField(
        max_length=255, verbose_name="Описание",
        blank=True, null=True,
    )
    diafilm_page = models.ForeignKey(
        "core.DiafilmPage", related_name="day", on_delete=models.CASCADE,
        verbose_name="Страница диафильма",
    )

    panels = (
        FieldRowPanel([
            FieldPanel("day"),
            FieldPanel("month"),
        ]),
        FieldPanel("description", classname="full"),
        PageChooserPanel("diafilm_page"),
    )

    class Meta:
        verbose_name = "Диафильм дня"
        verbose_name_plural = "Диафильмы дня"
        unique_together = ("day", "month", "diafilm_page", "description")
        ordering = ("month", "day")

    def __str__(self):
        return f"{self.diafilm_page_id}@{self.day}.{self.month}"

    def admin_title(self):
        return f"{self.day:02}.{self.month:02}"

    def next_date(self):
        today = timezone.now()
        result = today.replace(day=self.day, month=self.month)
        if result < today:
            result = result.replace(year=result.year + 1)

        return result

core/models/specific.py
"""

Диафильм дня
Документ
...


"""
from django.db import models

from wagtail_pointsblock.blocks import PointsStreamBlock


class Document(models.Model):
    """

    """
    pass


class Day(models.Model):
    """
    Для задания диафильма дня
    Год значения не имеет, будем выбирать экстрактом наверное
    Ну и получается один диафильм может к нескольким дня быть привязан
    """
    day = models.DateField(verbose_name="День и месяц", db_index=True)
    diafilm = models.ForeignKey(
        "Diafilm", related_name="day", on_delete=models.CASCADE,
        verbose_name="Диафильм", db_index=True,
    )
    description = models.TextField(
        verbose_name="Описание",
        help_text="Почему этот диафильм привязан к этому дню",
    )

    class Meta:
        verbose_name = "День"
        verbose_name_plural = "Дни"
        unique_together = ("day", "diafilm")
        ordering = ("day", )

core/views.py
import logging

import requests
from django import forms
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.mail import mail_managers
from django.http import HttpResponse, JsonResponse
from django.views.generic import FormView, ListView
from django.views.generic.edit import BaseFormView, CreateView, UpdateView
from django_filters import (BooleanFilter, CharFilter, ChoiceFilter, FilterSet,
                            NumberFilter)
from django_filters.views import FilterView

from core.models import (ArtistPage, CollectionPage, Diafilm, DiafilmPage,
                         Location, NewsPage, Subscription)
from etl.diafilm import ApiDiafilm

logger = logging.getLogger(__name__)


class SuperUserRequiredMixin(LoginRequiredMixin, UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_superuser


class ImportForm(forms.Form):
    """
    Можно сюда накопировать хэндлы построчно
    и мы их все создадим/обновим через апишку РГДБ
    """
    handles = forms.CharField(
        label="Хэндлы",
        widget=forms.Textarea(attrs={"rows": 6}),
    )

    def is_valid(self):
        if super().is_valid():
            self.save()

    def request(self, handle_id):
        data = None
        url = f"https://arch.rgdb.ru/rest/items/{handle_id}/metadata"

        try:
            response = requests.get(url)
        except Exception as exc:
            pass
        else:
            if response.status_code != 404:
                data = response.json()

        return data

    def save_object(self, handle_id, data):
        try:
            obj = ApiDiafilm.from_json(
                doc_id=handle_id,
                data=data,
            )
            obj = Diafilm.from_api(obj)
            Diafilm.objects.update_or_create(
                eid=obj["eid"],
                defaults=obj,
            )
        except Exception as exc:
            logger.error(
                "Import failed: %s (%s, %s)",
                exc, handle_id, data,
                exc_info=True,
            )

    def save(self):
        """
        По каждому надо сделать запрос
        https://arch.rgdb.ru/rest/items/36365/metadata

        Если что, кинем в арк, там совсем асинк
        """
        handles = self.cleaned_data.get("handles", "").split()
        for handle_id in handles:
            data = self.request(handle_id)
            self.save_object(handle_id, data)

        # ASYNC-версия
        # from arq.constants import default_queue_name
        # params = settings.ARQ_QUEUES[default_queue_name]

        # import asyncio
        # from arq import create_pool
        # redis = asyncio.run(create_pool(**params))

        # loop = asyncio.new_event_loop()
        # redis = loop.run_until_complete(create_pool(params))
        # loop.run_until_complete(redis.enqueue_job('fetch_handle_data', handles))


class ImportView(SuperUserRequiredMixin, FormView):
    """
    В проде не будет дампа базы РГДБ
    так что придётся брать большую часть данных из API
    в котором тоже кое-чего может не быть
    """
    template_name = "core/import.html"
    form_class = ImportForm


class JsonForm:
    def form_valid(self, form):
        return JsonResponse({
            "success": True,
            "data": {},
        }, status=200)

    def form_invalid(self, form):
        errors = form.errors
        return JsonResponse({
            "success": False,
            "data": errors,
        }, status=400)


class ContactForm(forms.Form):
    email = forms.EmailField()
    subject = forms.CharField(max_length=100)
    message = forms.CharField(max_length=1000)
    attachment = forms.FileField(required=False)


class ContactView(JsonForm, BaseFormView):
    """
    Обрабатывает данные из формы для обратной связи с фронта
    """
    form_class = ContactForm

    def form_valid(self, form):
        # TODO: rewrite
        mail_managers(
            form.cleaned_data["subject"],
            form.cleaned_data["message"],
            fail_silently=False,
            connection=None,
            html_message=None,
        )

        return super().form_valid(form)

    def get(self, request, *args, **kwargs):
        return HttpResponse("", status=405)


class SubscriptionForm(forms.ModelForm):

    class Meta:
        model = Subscription
        fields = ("email", )

    def save(self, commit=True):
        self.instance.status = Subscription.STATUS_NEW
        return super(SubscriptionForm, self).save(commit)


class SubscriptionView(JsonForm, CreateView):
    form_class = SubscriptionForm


class UnsubscriptionForm(forms.ModelForm):
    class Meta:
        model = Subscription
        fields = ("email", )

    def save(self, commit=True):
        self.instance.status = Subscription.STATUS_REJECTED
        super().save(commit)


class UnsubscriptionView(JsonForm, UpdateView):
    form_class = UnsubscriptionForm


class CustomChoiceFilter(ChoiceFilter):
    def __init__(self, *args, **kwargs):
        self.any_value = kwargs.pop("any_value", None)
        if self.any_value:
            choices = kwargs.get("choices", ())
            kwargs["choices"] = ((self.any_value, "Any"), ) + choices

        super().__init__(*args, **kwargs)

    def filter(self, qs, value):
        if self.any_value and value == self.any_value:
            return qs

        return super().filter(qs, value)


class NewsFilter(FilterSet):
    category = CustomChoiceFilter(choices=NewsPage.CATEGORY_CHOICES, any_value="all")

    def filter_queryset(self, queryset):
        result = super().filter_queryset(queryset)
        return result


class NewsListView(FilterView, ListView):
    template_name = "components/news/list.html"
    queryset = NewsPage.objects.live().public()
    ordering = ("-published_at", "-pk")
    filterset_class = NewsFilter

    paginate_by_default = 3 * 3
    paginate_by = paginate_by_default
    allow_empty = True

    def get_filterset(self, filterset_class):
        fs = super().get_filterset(filterset_class)
        return fs


class DiafilmFilter(FilterSet):
    query = CharFilter(field_name="title", lookup_expr="icontains")
    person = CharFilter(field_name="diafilm__roles__person_id", lookup_expr="exact")

    is_school = BooleanFilter(field_name="diafilm__doc__schoolsubj", method="filter_is_school")
    subject = CharFilter(field_name="diafilm__doc__schoolsubj", lookup_expr="iexact")
    level = CharFilter(field_name="diafilm__doc__schoollevel", lookup_expr="iexact")

    def filter_is_school(self, queryset, name, value):
        return queryset.exclude(**{name: value})

    def filter_queryset(self, queryset):
        result = super().filter_queryset(queryset)
        return result

        if search_query is not None:
            multimatch.append({
                "query": search_query,
                "fields": [
                    "title",
                    # "categories^2",
                    # "description^0.5",
                    # "persons.role^1",
                    # "persons.name^3",
                ],
                "type": "best_fields",
                "operator": "OR",
                "fuzziness": "AUTO",
                "prefix_length": 2,
                "max_expansions": 3,
            })

        subject = ""
        if subject:
            multimatch.append({
                "query": search_query,
                "fields": [
                    "title",
                    # "categories^2",
                    # "description^0.5",
                    # "persons.role^1",
                    # "persons.name^3",
                ],
                "type": "best_fields",
                "operator": "OR",
                "fuzziness": "AUTO",
                "prefix_length": 2,
                "max_expansions": 3,
            })

        query = {
            "bool": {
                "should": [
                    {
                        "multi_match": {
                            "query": search_query,
                            "fields": [
                                "title^3",
                                "categories^2",
                                "description^0.5",
                                "persons.role^1",
                                "persons.name^3",
                            ],
                            "type": "best_fields",
                            "operator": "OR",
                            "fuzziness": "AUTO",
                            "prefix_length": 2,
                            "max_expansions": 3,
                        }
                    },
                    {
                        "multi_match": {
                            "query": search_query,
                            "fields": [
                                "_id",
                                "handle",
                            ]
                        }
                    },
                ]
            }
        }

        es = get_elasticsearch()
        search_results = es.search(
            index=settings.ELASTICSEARCH_INDEX,
            query=query,
            size=per_page,
            from_=per_page * (page - 1),
        )
        total = search_results["hits"]["total"]["value"]

        # search_results = Page.objects.live().search(search_query)
        # query = Query.get(search_query)

        # Record hit
        # query.add_hit()


class DiafilmListView(FilterView, ListView):
    template_name = "components/diafilms/list.html"
    queryset = DiafilmPage.objects.live().public()
    ordering = ("title", )
    filterset_class = DiafilmFilter

    paginate_by_default = 3 * 4
    paginate_by = paginate_by_default
    allow_empty = True

    # def get_filterset(self, filterset_class):
    #     fs = super().get_filterset(filterset_class)
    #     return fs


class CollectionListView(ListView):
    template_name = "components/collections/list.html"
    queryset = CollectionPage.objects.live().public()

core/templates/components/artifact_similar.html
{% load core_tags %}
{% load content_tags %}

{% get_equipment_similar page ordering="?" as object_list %}

{% if object_list %}
<div class="similar similar_{% if not page.is_index %}{{ page.html_class }}{% else %}default{% endif %}">
    <div class="similar__container">
        <div class="similar__row">
            {% if title %}
            <div class="similar__label">{{ title|format_title }}</div>
            {% endif %}

            {% if text %}
            <div class="similar__text">{{ text }}</div>
            {% endif %}

            <div class="similar__carousel carousel carousel_models js-carousel-horizontal">
                <div class="carousel__viewport js-carousel-viewport">
                    <ul class="carousel__list js-carousel-overflow">
                        {% for item in object_list %}
                        <li class="carousel__item carousel__item_default js-carousel-item">
                            <article class="card card_model" data-clickable>
                                <div class="card__picture">
                                    {% with class="card__image" format="png" %}
                                    {% include "common/img.html" with img=item.photo size="fill-288x288" %}
                                    {% endwith %}
                                </div>
                                <div class="card__body">
                                    <div class="card__label" role="heading" aria-level="4">
                                        <a class="card__link" href="{{ item.url }}">
                                            {{ item.title|format_title }}
                                        </a>
                                    </div>
                                </div>
                            </article>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}

core/templates/components/carousel.html
{% load common_tags %}

{% if title %}
<div class="text text_small">
    <div class="text__body is-editable">
        <h3>{{ title|format_title }}</h3>
    </div>
</div>
{% endif %}

<div class="carousel carousel_facts js-carousel-horizontal">
    <div class="carousel__viewport js-carousel-viewport">
        <ul class="carousel__list js-carousel-overflow">
            {% for item in items %}
            <li class="carousel__item carousel__item_default js-carousel-item">
                <article class="card card_fact">
                    <div class="card__picture">
                        {% with size="fill-272x200" class="card__image" %}
                        {% include "common/img.html" with img=item %}
                        {% endwith %}
                    </div>
                    <div class="card__body">
                        <div class="card__text">{{ item.title|format_title }}</div>
                    </div>
                </article>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

core/templates/components/contacts_great.html
{% load common_tags %}
<div class="columns columns_contacts">
    <div class="columns">
        <div class="columns__container">
            <div class="columns__row">
                {% if object.form_show %}
                <div class="columns__column columns__column_1">
                    <form class="form form_default form_feedback js-form-feedback"
                          action="{% url "api:contact" %}" enctype="multipart/form-data" method="post">
                        {% csrf_token %}
                        {% if object.form_title %}
                        <div class="form__header">
                            <div class="form__label" role="heading" aria-level="2">
                                {{ object.form_title|format_title }}
                            </div>
                        </div>
                        {% endif %}
                        <div class="form__body">
                            <div class="form__field form__field_default">
                                <div class="field field_default js-form-field">
                                    <label class="field__label js-form-field-label" for="id_feedback_email">Электронная почта*</label>
                                    <input class="field__element field__element_email is-email is-required is-external-email js-form-field-element" type="email" name="email" id="id_feedback_email">
                                    <label class="field__error js-form-field-error" for="id_feedback_email" id="id_feedback_email-error" aria-hidden="true"></label>
                                </div>
                            </div>
                            <div class="form__field form__field_default">
                                <div class="field field_default js-form-field">
                                    <label class="field__label js-form-field-label" for="id_feedback_subject">Тема</label>
                                    <input class="field__element field__element_text is-string is-external-subject js-form-field-element" type="text" name="subject" id="id_feedback_subject">
                                    <label class="field__error js-form-field-error" for="id_feedback_subject" id="id_feedback_subject-error" aria-hidden="true"></label>
                                </div>
                            </div>
                            <div class="form__field form__field_default">
                                <div class="field field_default field_multiline js-form-field">
                                    <label class="field__label js-form-field-label" for="id_feedback_message">Ваше сообщение*</label>
                                    <textarea class="field__element field__element_multiline is-message is-required is-external-message js-form-field-element" name="message" id="id_feedback_message"></textarea>
                                    <label class="field__placeholder js-form-field-placeholder" for="id_feedback_message">Ваше сообщение</label>
                                    <label class="field__error js-form-field-error" for="id_feedback_message" id="id_feedback_message-error" aria-hidden="true"></label>
                                </div>
                            </div>
                            <div class="form__field form__field_default">
                                <div class="field field_file js-form-field js-form-field-file">
                                    <label class="field__label js-form-field-label" for="id_feedback_attachments">
                                        <span>Прикрепить файл</span>
                                    </label>
                                    <input class="field__element field__element_file is-file-size:3072000 is-file-quantity:3 is-external-attachments js-form-field-element" type="file" name="attachments" id="id_feedback_attachments" tabindex="-1" accept="image/png,image/jpeg,application/pdf,.doc,.docx" multiple>
                                    <label class="field__value js-form-field-value" for="id_feedback_attachments"></label>
                                    <label class="field__error js-form-field-error" for="id_feedback_attachments" id="id_feedback_attachments-error" aria-hidden="true"></label>
                                </div>
                            </div>
                            <div class="form__field form__field_default">
                                <button class="button button_outline" type="submit">
                                    <span class="button__label">Отправить письмо</span>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
                {% endif %}
                <div class="columns__column columns__column_2">
                    <div class="contacts contacts_default">
                        <div class="contacts">
                            <div class="contacts__container">
                                <div class="contacts__row">
                                    <div class="contacts__label" role="heading" aria-level="3">
                                        {{ object.title|format_title }}
                                    </div>
                                    <div class="contacts__text is-editable">
                                        {{ object.text }}
                                    </div>

                                    {% if object.email %}
                                    <div class="contacts__contact">
                                        <a class="contacts__link" href="mailto:{{ object.email }}" target="_blank" rel="noopener noreferrer">{{ object.email }}</a>
                                    </div>
                                    {% endif %}

                                    {% if object.phone %}
                                    <div class="contacts__contact">
                                        <a class="contacts__link" href="tel:{{ object.phone|phone_raw }}">{{ object.phone }}</a>
                                    </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

core/templates/components/diafilm_viewer.html
<div class="diafilm__viewport">
    <div class="diafilm__player js-diafilm-player">
        {% if page.diafilm.handle_id %}
        <iframe class="diafilm__iframe js-diafilm-iframe" allowfullscreen
                src="{{ page.diafilm.url }}">
        </iframe>
            <button class="diafilm__button diafilm__button_exit js-diafilm-exit" type="button" aria-label="Назад" title="Назад"></button>
        {% else %}
        <p>Диафильм временно недоступен</p>
        {% endif %}
    </div>
    <div class="diafilm__toolbar">
        <button class="diafilm__button diafilm__button_full js-diafilm-full" type="button">На весь экран</button>
        <div class="diafilm__nav">
            <button class="diafilm__button diafilm__button_up js-diafilm-up" type="button" aria-label="Вверх" title="Вверх"></button>
            <div class="diafilm__hint">Следующий кадр</div>
            <button class="diafilm__button diafilm__button_down js-diafilm-down" type="button" aria-label="Вниз" title="Вниз"></button>
        </div>
    </div>
</div>

core/templates/components/globe.html
{% load common_tags %}

<div class="earth earth_inner js-earth"
     data-cards="{% url "api:globe-cards" %}"
     data-points="{% url "api:globe-points" %}">
    <div class="earth__container">
        <div class="earth__row">
            <div class="earth__header">
                <div class="earth__label" role="heading" aria-level="3">{{ self.title|format_title }}</div>
                <div class="earth__text is-editable">
                    {{ self.text }}
                </div>
                <div class="earth__carousel carousel carousel_earth js-carousel-earth">
                    <form class="carousel__filter form form_filter js-carousel-filter">
                        <div class="form__body">
                            <div class="form__field form__field_full">
                                <div class="field field_select js-form-field js-form-field-select">
                                    <label class="field__label js-form-field-label" for="id_form_country">Сказки
                                        континентов мира</label>
                                    <select
                                        class="field__element field__element_select is-external-country js-form-field-element"
                                        name="country" id="id_form_country" tabindex="-1">
                                        <option value="">Все</option>
                                    </select>
                                    <label class="field__value js-form-field-value" for="id_form_country" tabindex="0">Все</label>
                                </div>
                            </div>
                            <div class="form__field form__field_full">
                                <div class="field field_select js-form-field js-form-field-select">
                                    <label class="field__label js-form-field-label" for="id_form_district">Сказки
                                        России</label>
                                    <select
                                        class="field__element field__element_select is-external-district js-form-field-element"
                                        name="district" id="id_form_district" tabindex="-1" disabled>
                                        <option value="">Все</option>
                                    </select>
                                    <label class="field__value js-form-field-value" for="id_form_district" tabindex="0">Все</label>
                                </div>
                            </div>
                        </div>
                    </form>
                    <div class="carousel__viewport js-carousel-viewport">
                        <ul class="carousel__list js-carousel-overflow">
                        </ul>
                    </div>
                </div>
            </div>
            <div class="earth__viewport">
                <div class="earth__player js-earth-player"></div>
                <div class="earth__hint js-earth-hint"></div>
            </div>
        </div>
    </div>
</div>

core/templates/components/menu_great.html
{% load wagtailcore_tags %}
{% load common_tags %}
{% load navigation_tags %}

{% wagtail_site as site %}

<nav class="title__nav">
    {% for item in menu_root.menu_children %}
    <a class="title__button {% if page.html_class == item.html_class %}is-active{% endif %}" href="{{ item.get_menu_url }}">
        <span>{{ item.get_menu_title|format_title }}</span>
    </a>
    {% endfor %}
</nav>