application/urls.py
from django.conf import settings
from django.contrib import admin
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import include, path
from django.views.decorators.cache import cache_page
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.contrib.sitemaps.views import sitemap
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views

urlpatterns = [
    path('api/', include("wagtail_typograf.urls")),
    path('api/', include("core.urls", namespace="api")),
    path('django-admin/', admin.site.urls),

    path('admin/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),

    path('sitemap.xml', cache_page(15 * 60)(sitemap), name="sitemap"),
]


if "debug_toolbar" in settings.INSTALLED_APPS:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('search/', search_views.search, name='search'),
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]


def robots(request):
    return render(request, "pages/robots.txt", content_type="text/plain")


def healthcheck(request):
    from application import VERSION
    return JsonResponse({
        "status": "live",
        "version": VERSION,
    })


urlpatterns = [
    path("robots.txt", robots, name="robots"),
    path("healthcheck/", healthcheck, name="healthcheck"),
] + urlpatterns

core/urls.py
from django.urls import path

from core.views import (ArtistListView, CollectionListView, ContactView,
                        DiafilmListView, GlobeCardListView, GlobePointListView,
                        ImportView, NewsListView, SubscriptionView,
                        UnsubscriptionView)

app_name = "core"


urlpatterns = [
    path("import/", ImportView.as_view(), name="import"),

    path("contact/", ContactView.as_view(), name="contact"),
    path("subscribe/", SubscriptionView.as_view(), name="subscribe"),
    path("unsubscribe/", UnsubscriptionView.as_view(), name="unsubscribe"),

    path("news/", NewsListView.as_view(), name="news"),
    path("artists/", ArtistListView.as_view(), name="artists"),
    path("diafilms/", DiafilmListView.as_view(), name="diafilms"),
    path("collections/", CollectionListView.as_view(), name="collections"),

    path("points/", GlobePointListView.as_view(), name="globe-points"),
    path("cards/", GlobeCardListView.as_view(), name="globe-cards"),
]

core/models/snippets.py
from django.core.cache import cache
from django.db import models
from django.utils import timezone
from wagtail.admin.edit_handlers import (FieldPanel, FieldRowPanel,
                                         PageChooserPanel)
from wagtail.core.fields import StreamField
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.snippets.models import register_snippet

from core.blocks import RawStreamBlock


@register_snippet
class Chunk(models.Model):
    slug = models.SlugField(
        help_text="Строка, по которой данный chunk можно использовать в шаблоне",
    )
    description = models.TextField(
        help_text="Описание для администратора, где отображается и так далее",
        blank=True,
    )

    content = StreamField(
        verbose_name="Содержание",
        block_types=RawStreamBlock,
        blank=True, null=True,
    )

    panels = [
        FieldPanel("slug"),
        FieldPanel("description"),
        FieldPanel("content"),
    ]

    def __str__(self):
        return f"Вставка {self.slug}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        from core.templatetags.chunk_tags import get_chunk
        cache.delete(get_chunk.cache_key)

    class Meta:
        verbose_name = "вставка"
        verbose_name_plural = "вставки"


@register_snippet
class Quote(models.Model):
    author = models.CharField(verbose_name="Автор", max_length=100)
    image = models.ForeignKey(
        'wagtailimages.Image', related_name='+', on_delete=models.SET_NULL,
        null=True, blank=True,
        verbose_name="Изображение",
    )
    caption = models.CharField(verbose_name="Подпись", max_length=100)
    text = models.TextField(verbose_name="Текст")
    # source = models.CharField(verbose_name="Источник", max_length=50)

    panels = [
        FieldPanel("author"),
        ImageChooserPanel("image"),
        FieldPanel("caption"),
        FieldPanel("text"),
    ]

    def __str__(self):
        return f"«{self.text}» {self.author}, {self.caption}"

    class Meta:
        verbose_name = "цитата"
        verbose_name_plural = "цитаты"


class Day(models.Model):
    """
    Для рубрики Диафильм дня
    """
    day = models.IntegerField(verbose_name="День")
    month = models.IntegerField(verbose_name="Месяц")
    description = models.CharField(
        max_length=255, verbose_name="Описание",
        blank=True, null=True,
    )
    diafilm_page = models.ForeignKey(
        "core.DiafilmPage", related_name="day", on_delete=models.CASCADE,
        verbose_name="Страница диафильма",
    )

    panels = (
        FieldRowPanel([
            FieldPanel("day"),
            FieldPanel("month"),
        ]),
        FieldPanel("description", classname="full"),
        PageChooserPanel("diafilm_page"),
    )

    class Meta:
        verbose_name = "Диафильм дня"
        verbose_name_plural = "Диафильмы дня"
        unique_together = ("day", "month", "diafilm_page", "description")
        ordering = ("month", "day")

    def __str__(self):
        return f"{self.diafilm_page_id}@{self.day}.{self.month}"

    def admin_title(self):
        return f"{self.day:02}.{self.month:02}"

    def next_date(self):
        today = timezone.now()
        result = today.replace(day=self.day, month=self.month)
        if result < today:
            result = result.replace(year=result.year + 1)

        return result

core/models/specific.py
"""

Диафильм дня
Документ
...


"""
from django.db import models

from wagtail_pointsblock.blocks import PointsStreamBlock


class Document(models.Model):
    """

    """
    pass


class Day(models.Model):
    """
    Для задания диафильма дня
    Год значения не имеет, будем выбирать экстрактом наверное
    Ну и получается один диафильм может к нескольким дня быть привязан
    """
    day = models.DateField(verbose_name="День и месяц", db_index=True)
    diafilm = models.ForeignKey(
        "Diafilm", related_name="day", on_delete=models.CASCADE,
        verbose_name="Диафильм", db_index=True,
    )
    description = models.TextField(
        verbose_name="Описание",
        help_text="Почему этот диафильм привязан к этому дню",
    )

    class Meta:
        verbose_name = "День"
        verbose_name_plural = "Дни"
        unique_together = ("day", "diafilm")
        ordering = ("day", )

core/views.py
import logging

import requests
from django import forms
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.mail import mail_managers
from django.http import HttpResponse, JsonResponse
from django.views.generic import FormView, ListView
from django.views.generic.edit import BaseFormView, CreateView, UpdateView
from django_filters import (BooleanFilter, CharFilter, ChoiceFilter, FilterSet,
                            NumberFilter)
from django_filters.views import FilterView

from core.models import (ArtistPage, CollectionPage, Diafilm, DiafilmPage,
                         Location, NewsPage, Subscription)
from etl.diafilm import ApiDiafilm

logger = logging.getLogger(__name__)


class SuperUserRequiredMixin(LoginRequiredMixin, UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_superuser


class ImportForm(forms.Form):
    """
    Можно сюда накопировать хэндлы построчно
    и мы их все создадим/обновим через апишку РГДБ
    """
    handles = forms.CharField(
        label="Хэндлы",
        widget=forms.Textarea(attrs={"rows": 6}),
    )

    def is_valid(self):
        if super().is_valid():
            self.save()

    def request(self, handle_id):
        data = None
        url = f"https://arch.rgdb.ru/rest/items/{handle_id}/metadata"

        try:
            response = requests.get(url)
        except Exception as exc:
            pass
        else:
            if response.status_code != 404:
                data = response.json()

        return data

    def save_object(self, handle_id, data):
        try:
            obj = ApiDiafilm.from_json(
                doc_id=handle_id,
                data=data,
            )
            obj = Diafilm.from_api(obj)
            Diafilm.objects.update_or_create(
                eid=obj["eid"],
                defaults=obj,
            )
        except Exception as exc:
            logger.error(
                "Import failed: %s (%s, %s)",
                exc, handle_id, data,
                exc_info=True,
            )

    def save(self):
        """
        По каждому надо сделать запрос
        https://arch.rgdb.ru/rest/items/36365/metadata

        Если что, кинем в арк, там совсем асинк
        """
        handles = self.cleaned_data.get("handles", "").split()
        for handle_id in handles:
            data = self.request(handle_id)
            self.save_object(handle_id, data)

        # ASYNC-версия
        # from arq.constants import default_queue_name
        # params = settings.ARQ_QUEUES[default_queue_name]

        # import asyncio
        # from arq import create_pool
        # redis = asyncio.run(create_pool(**params))

        # loop = asyncio.new_event_loop()
        # redis = loop.run_until_complete(create_pool(params))
        # loop.run_until_complete(redis.enqueue_job('fetch_handle_data', handles))


class ImportView(SuperUserRequiredMixin, FormView):
    """
    В проде не будет дампа базы РГДБ
    так что придётся брать большую часть данных из API
    в котором тоже кое-чего может не быть
    """
    template_name = "core/import.html"
    form_class = ImportForm


class JsonForm:
    def form_valid(self, form):
        return JsonResponse({
            "success": True,
            "data": {},
        }, status=200)

    def form_invalid(self, form):
        errors = form.errors
        return JsonResponse({
            "success": False,
            "data": errors,
        }, status=400)


class ContactForm(forms.Form):
    email = forms.EmailField()
    subject = forms.CharField(max_length=100)
    message = forms.CharField(max_length=1000)
    attachment = forms.FileField(required=False)


class ContactView(JsonForm, BaseFormView):
    """
    Обрабатывает данные из формы для обратной связи с фронта
    """
    form_class = ContactForm

    def form_valid(self, form):
        # TODO: rewrite
        mail_managers(
            form.cleaned_data["subject"],
            form.cleaned_data["message"],
            fail_silently=False,
            connection=None,
            html_message=None,
        )

        return super().form_valid(form)

    def get(self, request, *args, **kwargs):
        return HttpResponse("", status=405)


class SubscriptionForm(forms.ModelForm):

    class Meta:
        model = Subscription
        fields = ("email", )

    def save(self, commit=True):
        self.instance.status = Subscription.STATUS_NEW
        return super(SubscriptionForm, self).save(commit)


class SubscriptionView(JsonForm, CreateView):
    form_class = SubscriptionForm


class UnsubscriptionForm(forms.ModelForm):
    class Meta:
        model = Subscription
        fields = ("email", )

    def save(self, commit=True):
        self.instance.status = Subscription.STATUS_REJECTED
        super().save(commit)


class UnsubscriptionView(JsonForm, UpdateView):
    form_class = UnsubscriptionForm


class CustomChoiceFilter(ChoiceFilter):
    def __init__(self, *args, **kwargs):
        self.any_value = kwargs.pop("any_value", None)
        if self.any_value:
            choices = kwargs.get("choices", ())
            kwargs["choices"] = ((self.any_value, "Any"), ) + choices

        super().__init__(*args, **kwargs)

    def filter(self, qs, value):
        if self.any_value and value == self.any_value:
            return qs

        return super().filter(qs, value)


class NewsFilter(FilterSet):
    category = CustomChoiceFilter(choices=NewsPage.CATEGORY_CHOICES, any_value="all")

    def filter_queryset(self, queryset):
        result = super().filter_queryset(queryset)
        return result


class NewsListView(FilterView, ListView):
    template_name = "components/news/list.html"
    queryset = NewsPage.objects.live().public()
    ordering = ("-published_at", "-pk")
    filterset_class = NewsFilter

    paginate_by_default = 3 * 3
    paginate_by = paginate_by_default
    allow_empty = True

    def get_filterset(self, filterset_class):
        fs = super().get_filterset(filterset_class)
        return fs


class DiafilmFilter(FilterSet):
    query = CharFilter(field_name="title", lookup_expr="icontains")
    person = CharFilter(field_name="diafilm__roles__person_id", lookup_expr="exact")

    is_school = BooleanFilter(field_name="diafilm__doc__schoolsubj", method="filter_is_school")
    subject = CharFilter(field_name="diafilm__doc__schoolsubj", lookup_expr="iexact")
    level = CharFilter(field_name="diafilm__doc__schoollevel", lookup_expr="iexact")

    def filter_is_school(self, queryset, name, value):
        return queryset.exclude(**{name: value})

    def filter_queryset(self, queryset):
        result = super().filter_queryset(queryset)
        return result

        if search_query is not None:
            multimatch.append({
                "query": search_query,
                "fields": [
                    "title",
                    # "categories^2",
                    # "description^0.5",
                    # "persons.role^1",
                    # "persons.name^3",
                ],
                "type": "best_fields",
                "operator": "OR",
                "fuzziness": "AUTO",
                "prefix_length": 2,
                "max_expansions": 3,
            })

        subject = ""
        if subject:
            multimatch.append({
                "query": search_query,
                "fields": [
                    "title",
                    # "categories^2",
                    # "description^0.5",
                    # "persons.role^1",
                    # "persons.name^3",
                ],
                "type": "best_fields",
                "operator": "OR",
                "fuzziness": "AUTO",
                "prefix_length": 2,
                "max_expansions": 3,
            })

        query = {
            "bool": {
                "should": [
                    {
                        "multi_match": {
                            "query": search_query,
                            "fields": [
                                "title^3",
                                "categories^2",
                                "description^0.5",
                                "persons.role^1",
                                "persons.name^3",
                            ],
                            "type": "best_fields",
                            "operator": "OR",
                            "fuzziness": "AUTO",
                            "prefix_length": 2,
                            "max_expansions": 3,
                        }
                    },
                    {
                        "multi_match": {
                            "query": search_query,
                            "fields": [
                                "_id",
                                "handle",
                            ]
                        }
                    },
                ]
            }
        }

        es = get_elasticsearch()
        search_results = es.search(
            index=settings.ELASTICSEARCH_INDEX,
            query=query,
            size=per_page,
            from_=per_page * (page - 1),
        )
        total = search_results["hits"]["total"]["value"]

        # search_results = Page.objects.live().search(search_query)
        # query = Query.get(search_query)

        # Record hit
        # query.add_hit()


class DiafilmListView(FilterView, ListView):
    template_name = "components/diafilms/list.html"
    queryset = DiafilmPage.objects.live().public()
    ordering = ("title", )
    filterset_class = DiafilmFilter

    paginate_by_default = 3 * 4
    paginate_by = paginate_by_default
    allow_empty = True

    # def get_filterset(self, filterset_class):
    #     fs = super().get_filterset(filterset_class)
    #     return fs


class CollectionListView(ListView):
    template_name = "components/collections/list.html"
    queryset = CollectionPage.objects.live().public()

core/templates/components/artists/base.html
{% load wagtailcore_tags %}
{% load common_tags %}
{% load content_tags %}

{% get_artist_pages count=count ordering=ordering as list_page %}

<section class="feed feed_artists {% if show_paging %}js-feed-lazy{% endif %} {% if class %}feed_{{ class }}{% endif %}">
    <div class="feed__container">
        <div class="feed__row">
            <div class="feed__header">
                <div class="feed__label" role="heading" aria-level="2">
                    {{ title|format_title }}
                </div>
                <div class="feed__text">{{ text }}</div>
            </div>

            {% if show_search %}
            {% include "components/artists/form.html" %}
            {% endif %}

            {% if show_filter %}
            {% include "components/artists/filter.html" %}
            {% endif %}

            <div class="feed__list {% if show_paging %}js-feed-list{% endif %}">
                <div class="feed__item feed__item_default js-feed-item">
                    <div class="artists artists_default">
                        {% for part in list_page.object_list|chunks:"4" %}
                        <div class="artists__list">
                            {% include "components/artists/list.html" with object_list=part %}
                        </div>
                        {% endfor %}

                        {% if show_link %}
                        <div class="artists__after">
                            <a class="artists__more" href="{% slugurl "gallery" %}">Пройти в&nbsp;галерею</a>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>

            {% if show_paging and list_page.has_next %}
            <div class="feed__pagination">
                <a class="feed__button feed__button_more button button_inline js-feed-button"
                   href="?page={{ list_page.next_page_number }}" data-base="{% url "api:artists" %}" rel="next">
                    <span class="button__icon button__icon_before button__icon_arrow-down"></span>
                    <span class="button__label">Загрузить ещё</span>
                </a>
            </div>
            {% endif %}
        </div>
    </div>
</section>

core/templates/components/artists/detail.html
<div class="artists__item">
    <article class="artist artist_default">
        {% if item.sample %}
        <div class="artist__picture">
            {% include "common/img.html" with img=item.sample size=size class="artist__img" %}
        </div>
        {% endif %}

        {% if item.photo %}
        <div class="artist__photo">
            {% include "common/img.html" with img=item.photo size="fill-120x150" class="artist__img" filters="grayscale" %}
        </div>
        {% endif %}

        <div class="artist__label" role="heading" aria-level="4">
            {{ item.person.full_name }}
        </div>
        <div class="artist__text">
            {{ item.annotation }}
        </div>
        <a class="artist__link" href="{{ item.url }}">
            Подробнее
        </a>
    </article>
</div>

core/templates/components/artists/filter.html
{% load common_tags %}
{% load wagtailcore_tags %}
{% load content_tags %}

{% get_artists roles=roles as object_list %}

<div class="feed__tags">
    <!--
    <a class="feed__button_filter button button_tag is-active" href="#">
        <span class="button__label">Все&nbsp;
            <span>1434</span>
        </span>
    </a>
    -->
    {% for item in object_list %}
    <a class="feed__button_tag button button_tag" href="{% slugurl "viewing-hall" %}?person={{ item.pk }}">
        <span class="button__label">
            {{ item.full_name|format_title }}
            <span>{{ item.diafilms_count }}</span>
        </span>
    </a>
    {% endfor %}
</div>

core/templates/components/artists/form.html
<form class="feed__form form form_search js-form-search" action="" method="get">
    <div class="form__body">
        <div class="form__field form__field_full">
            <div class="field field_default js-form-field has-button">
                <input class="field__element field__element_search is-string is-external-q js-form-field-element"
                       type="search" name="query" value="{{ request.GET.query }}" id="id_search_q">
                <button class="field__button button button_field"
                        type="submit" aria-label="Поиск" title="Поиск">
                    <span class="button__icon button__icon_search-black"></span>
                </button>
            </div>
        </div>
    </div>
</form>

core/templates/components/artists/list.html
{% for item in object_list %}
{% cycle "max-222x192" "max-237x226" "max-303x208" "max-163x196" as size %}
{% include "components/artists/detail.html" %}
{% endfor %}