application/urls.py
from django.conf import settings
from django.contrib import admin
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import include, path
from django.views.decorators.cache import cache_page
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.contrib.sitemaps.views import sitemap
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views

urlpatterns = [
    path('api/', include("wagtail_typograf.urls")),
    path('api/', include("core.urls", namespace="api")),
    path('django-admin/', admin.site.urls),

    path('admin/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),

    path('sitemap.xml', cache_page(15 * 60)(sitemap), name="sitemap"),
]


if "debug_toolbar" in settings.INSTALLED_APPS:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('search/', search_views.search, name='search'),
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]


def robots(request):
    return render(request, "pages/robots.txt", content_type="text/plain")


def healthcheck(request):
    from application import VERSION
    return JsonResponse({
        "status": "live",
        "version": VERSION,
    })


urlpatterns = [
    path("robots.txt", robots, name="robots"),
    path("healthcheck/", healthcheck, name="healthcheck"),
] + urlpatterns

core/urls.py
from django.urls import path

from core.views import (ArtistListView, CollectionListView, ContactView,
                        DiafilmListView, GlobeCardListView, GlobePointListView,
                        ImportView, NewsListView, SubscriptionView,
                        UnsubscriptionView)

app_name = "core"


urlpatterns = [
    path("import/", ImportView.as_view(), name="import"),

    path("contact/", ContactView.as_view(), name="contact"),
    path("subscribe/", SubscriptionView.as_view(), name="subscribe"),
    path("unsubscribe/", UnsubscriptionView.as_view(), name="unsubscribe"),

    path("news/", NewsListView.as_view(), name="news"),
    path("artists/", ArtistListView.as_view(), name="artists"),
    path("diafilms/", DiafilmListView.as_view(), name="diafilms"),
    path("collections/", CollectionListView.as_view(), name="collections"),

    path("points/", GlobePointListView.as_view(), name="globe-points"),
    path("cards/", GlobeCardListView.as_view(), name="globe-cards"),
]

search/views.py
import json
from datetime import datetime

from django.conf import settings
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.template.response import TemplateResponse
from wagtail.core.models import Page

from core.models import get_elasticsearch


class Diafilm:
    def __init__(self, data):
        self.data = data

    def __getitem__(self, item):
        return self.source[item]

    # def __getattr__(self, item):
    #     return self.source[item]

    @property
    def id(self):
        return self.data["_id"]

    @property
    def source(self):
        return self.data["_source"]

    @property
    def diafilm_of_the_day(self):
        result = self.source["dates"].get("diafilm_of_the_day", None)
        result = result and datetime.fromisoformat(result)
        return result

    def issued_at(self):
        return datetime.fromisoformat(self.source["dates"]["issued"])

    def dlist(self):
        return (
            x["value"]
            for x in self.source["description"]
            if x["type"] != "provenance"
        )

    def as_json(self):
        return json.dumps(self.data, indent=4, ensure_ascii=False)


def search(request):
    per_page = 10
    search_query = request.GET.get("query", "")
    page = int(request.GET.get("page", 1))

    # Search
    if search_query == "":
        es = get_elasticsearch()
        search_results = es.search(
            index=settings.ELASTICSEARCH_INDEX,
            size=per_page,
            from_=per_page * (page - 1),
        )
        total = search_results["hits"]["total"]["value"]
    elif search_query is not None:
        query = {
            "bool": {
                "should": [
                    {
                        "multi_match": {
                            "query": search_query,
                            "fields": [
                                "title^3",
                                "categories^2",
                                "description^0.5",
                                "persons.role^1",
                                "persons.name^3",
                            ],
                            "type": "best_fields",
                            "operator": "OR",
                            "fuzziness": "AUTO",
                            "prefix_length": 2,
                            "max_expansions": 3,
                        }
                    },
                    {
                        "multi_match": {
                            "query": search_query,
                            "fields": [
                                "_id",
                                "handle",
                            ]
                        }
                    },
                ]
            }
        }

        es = get_elasticsearch()
        search_results = es.search(
            index=settings.ELASTICSEARCH_INDEX,
            query=query,
            size=per_page,
            from_=per_page * (page - 1),
        )
        total = search_results["hits"]["total"]["value"]

        # search_results = Page.objects.live().search(search_query)
        # query = Query.get(search_query)

        # Record hit
        # query.add_hit()
    else:
        search_results = Page.objects.none()

    # Pagination
    results = [""] * total
    results[(page - 1) * per_page:(page - 1) * per_page + per_page] = [
        Diafilm(x)
        for x in search_results["hits"]["hits"]
    ]
    paginator = Paginator(
        results,
        per_page,
    )
    try:
        results = paginator.page(page)
    except PageNotAnInteger:
        results = paginator.page(1)
    except EmptyPage:
        results = paginator.page(paginator.num_pages)

    siblings = 4
    return TemplateResponse(request, 'search/search.html', {
        'search_query': search_query,
        'search_results': results,
        'page_range': [
            x
            for x in results.paginator.page_range
            if x - siblings < results.number < x + siblings
        ],
    })

search/templates/search/search.html
{% extends "pages/detail.html" %}
{% load navigation_tags %}
{% load static wagtailcore_tags %}

{% block header_class %}header_gray{% endblock header_class %}
{% block main_class %}layout_gray{% endblock main_class %}
{% block footer_class %}footer_gray{% endblock footer_class %}

{% block main_header %}
<div class="diafilm diafilm_inner js-diafilm">
    <div class="diafilm__container">
        <div class="diafilm__row">
            <div class="diafilm__back">
                <a class="diafilm__link" href="{% get_back_url %}">Назад</a>
            </div>
        </div>
    </div>
</div>
<div class="title title_text">
    <div class="title__container">
        <div class="title__row">
            <h1 class="title__label">{{ page.title|format_title }}</h1>
        </div>
    </div>
</div>
{% endblock main_header %}

{% block main_content %}
<section class="feed feed_catalog js-feed-lazy">
    <div class="feed__container">
        <div class="feed__row">
            {% include "components/diafilms/form.html" %}
            <div class="feed__list js-feed-list">
                {% include "components/diafilms/list.html" with object_list=search_results %}
            </div>

            {% if list_page.has_next %}
            <div class="feed__pagination">
                <a class="feed__button feed__button_more button button_inline js-feed-button"
                   href="?page={{ list_page.next_page_number }}" data-base="{% url "api:diafilms" %}" rel="next">
                    <span class="button__icon button__icon_before button__icon_arrow-down"></span>
                    <span class="button__label">Загрузить ещё</span>
                </a>
            </div>
            {% endif %}
        </div>
    </div>
</section>


{% if request.user.is_staff %}
    <form action="{% url "search" %}" method="get">
        <input type="text" name="query"{% if search_query %} value="{{ search_query }}"{% endif %}>
        <input type="submit" value="Искать" class="button">
    </form>

    {% if search_results %}
        <hr>

        <p>
            Найдено {{ search_results.paginator.count }},
            страница {{ search_results.number }} / {{ search_results.paginator.num_pages }}
        </p>

        <ul>
            {% for result in search_results %}
                <li>
                    {#<h4><a href="{% pageurl result %}">{{ result }}</a></h4>#}
                    <h4>{{ result.title }}</h4>
                    <small>
                        ID: {{ result.id }} {{ result.handle.0 }}/{{ result.handle.1 }};
                        Диафильмов: {{ result.pages|length }} ({{ result.pages|join:", " }} кадров),
                        студия {{ result.publisher }},
                        {{ result.issued_at|date:"Y" }} год
                    </small>

                    <div style="width: fit-content;">
                        <div style="display: inline-block; border: 1px solid #EFEFEF; padding: 1px; width: 300px; min-height: 200px;">
                        <img src="{{ result.cover }}" alt="{{ result.title }} cover" style="display: block; width: 100%">
                        </div>
                        <div style="text-align: right;">
                            <a href="#" onclick="let el = this.parentElement.previousElementSibling.children[0]; let src = el.getAttribute('src'); let frame = src.match(/(\d+)\.jpg/)[1]; let n = parseInt(frame) - 1; nframe = String(n).padStart(frame.length, '0'); el.src = src.replace(frame, nframe); return false;">Назад</a>
                            <a href="#" onclick="let el = this.parentElement.previousElementSibling.children[0]; let src = el.getAttribute('src'); let frame = src.match(/(\d+)\.jpg/)[1]; let n = parseInt(frame) + 1; nframe = String(n).padStart(frame.length, '0'); el.src = src.replace(frame, nframe); return false;">Дальше</a>
                        </div>
                    </div>

                    {% for item in result.dlist %}
                    <p>{{ item|linebreaksbr }}</p>
                    {% endfor %}
                    {% if result.diafilm_of_the_day %}
                    <p>Будет диафильмом дня {{ result.diafilm_of_the_day|date:"j E Y" }} года</p>
                    {% endif %}

                    <h5>Категории</h5>
                    <ul>
                    {% for item in result.categories %}
                    <li>{{ item }}</li>
                    {% endfor %}
                    </ul>

                    <h5>Люди</h5>
                    <ul>
                    {% for item in result.persons %}
                    <li>{{ item.name }}, {{ item.role }}</li>
                    {% endfor %}
                    </ul>

                    <p>
                        <a href="#"
                           onclick="let target=this.parentElement.nextElementSibling; target.style.display=(target.style.display === 'none') ? 'block': 'none'; return false;">
                            source
                        </a>
                    </p>
                    <code style="display: none;"><pre>{{ result.as_json }}</pre></code>
                    {% if result.search_description %}
                        {{ result.search_description }}
                    {% endif %}
                </li>
            {% endfor %}
        </ul>

        <ul style="padding: 1px; border: 1px solid #EFEFEF;">
        {% if search_results.has_previous %}
            <li style="display: inline-block; margin: 1em;">
                <a href="{% url 'search' %}?query={{ search_query|urlencode }}&amp;page={{ search_results.previous_page_number }}">Предыдущая</a>
            </li>
        {% endif %}
        {% for page in page_range %}
            <li style="display: inline-block; margin: 1em;">
                {% if page == search_results.number %}
                    {{ page }}
                {% else %}
                    <a href="{% url 'search' %}?query={{ search_query|urlencode }}&amp;page={{ page }}">{{ page }}</a>
                {% endif %}
            </li>

        {% endfor %}
        {% if search_results.has_next %}
            <li style="display: inline-block; margin: 1em;">
                <a href="{% url 'search' %}?query={{ search_query|urlencode }}&amp;page={{ search_results.next_page_number }}">Следующая</a>
            </li>
        {% endif %}
        </ul>
    {% elif search_query %}
        Ничего не найдено
    {% endif %}
{% endif %}
{% endblock main_content %}